# Project identification
sonar.projectKey=IT21161056_secure-indentity-service
sonar.projectName=Secure Identity Service
sonar.organization=it21161056

# Source files
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**