# Project identification
sonar.projectKey=IT21161056_secure-indentity-service
sonar.projectName=Secure Identity Service
sonar.organization=it21161056

# Source files
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=secure-indentity-service
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8