name: Deploy Node API to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Navigate to API folder and install dependencies
        working-directory: ./identity-service
        run: npm install

      - name: Create .env file from GitHub Secrets
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> ./identity-service/.env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> ./identity-service/.env
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> ./identity-service/.env
          echo "PORT=${{ secrets.PORT }}" >> ./identity-service/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./identity-service/.env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> ./identity-service/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> ./identity-service/.env

      - name: Build the API (if needed)
        working-directory: ./identity-service
        run: npm run start # Update with your build command if applicable


      # - name: Build Docker image
      #   working-directory: ./identity-service
      #   run: |
      #     docker build -t your-dockerhub-username/identity-service:${{ github.sha }} .

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Push Docker image
      #   working-directory: ./identity-service
      #   run: |
      #     docker push your-dockerhub-username/identity-service:${{ github.sha }}

      # - name: Deploy to server (if applicable)
      #   run: |
      #     ssh user@your-server "docker pull your-dockerhub-username/identity-service:${{ github.sha }} && docker stop api-container || true && docker rm api-container || true && docker run --env-file /path/to/.env -d --name api-container -p 5000:5000 your-dockerhub-username/identity-service:${{ github.sha }}"
